CREATE TABLE Role (
    roleId INT AUTO_INCREMENT PRIMARY KEY,
    roleName VARCHAR(50) NOT NULL UNIQUE
);

CREATE TABLE AttendanceStatus (
    statusId INT AUTO_INCREMENT PRIMARY KEY,
    statusName VARCHAR(50) NOT NULL UNIQUE
);

CREATE TABLE ContextType (
    contextId INT AUTO_INCREMENT PRIMARY KEY,
    contextName VARCHAR(50) NOT NULL UNIQUE
);

CREATE TABLE ProfessorType (
    professorTypeId INT AUTO_INCREMENT PRIMARY KEY,
    professorTypeName VARCHAR(50) NOT NULL UNIQUE
);

CREATE TABLE YearLevel (
    yearLevelId INT AUTO_INCREMENT PRIMARY KEY,
    yearLevelName VARCHAR(50) NOT NULL UNIQUE
);

CREATE TABLE QuizType (
    quizTypeId INT AUTO_INCREMENT PRIMARY KEY,
    quizTypeName VARCHAR(50) NOT NULL UNIQUE
);

CREATE TABLE MissedQuizStatus (
    missedQuizStatusId INT AUTO_INCREMENT PRIMARY KEY,
    missedQuizStatusName VARCHAR(50) NOT NULL UNIQUE
);

CREATE TABLE DecisionType (
    decisionTypeId INT AUTO_INCREMENT PRIMARY KEY,
    decisionTypeName VARCHAR(100) NOT NULL UNIQUE
);

CREATE TABLE ExcuseStatus (
    excuseStatusId INT AUTO_INCREMENT PRIMARY KEY,
    excuseStatusName VARCHAR(50) NOT NULL UNIQUE
);